/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

/**
 *
 * @author filipe
 */
public class adminLogadoGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminLogadoGUI
     */
    public adminLogadoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnSistema = new javax.swing.JButton();
        jbtnAcervo = new javax.swing.JButton();
        jlpAcervo = new javax.swing.JLayeredPane();
        jtxtfTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnPesquisar = new javax.swing.JButton();
        jbtnListarTudo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnAddLivro = new javax.swing.JButton();
        jbtnRemoverLivro = new javax.swing.JButton();
        jbtnAlterarLivro = new javax.swing.JButton();
        jlpSistema = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jbtnPesquisarUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnAdicionarUser = new javax.swing.JButton();
        jbtnRemoverUser = new javax.swing.JButton();
        jbtnAlterarUser = new javax.swing.JButton();
        jbtnListarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Painel Admin");

        jLabel1.setText("Acessar:");

        jbtnSistema.setText("Sistema");
        jbtnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSistemaActionPerformed(evt);
            }
        });

        jbtnAcervo.setText("Acervo");
        jbtnAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAcervoActionPerformed(evt);
            }
        });

        jtxtfTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Título:");

        jbtnPesquisar.setText("Pesquisar Livro");
        jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisarActionPerformed(evt);
            }
        });

        jbtnListarTudo.setText("Listar todos os livros");
        jbtnListarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListarTudoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Livro", "Editora", "Autor", "Quantidade Total", "Disponível", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbtnAddLivro.setText("Adicionar Livro");

        jbtnRemoverLivro.setText("Remover livro");
        jbtnRemoverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverLivroActionPerformed(evt);
            }
        });

        jbtnAlterarLivro.setText("Alterar livro");
        jbtnAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlpAcervoLayout = new javax.swing.GroupLayout(jlpAcervo);
        jlpAcervo.setLayout(jlpAcervoLayout);
        jlpAcervoLayout.setHorizontalGroup(
            jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcervoLayout.createSequentialGroup()
                .addGroup(jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAcervoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jbtnPesquisar))
                    .addGroup(jlpAcervoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbtnAddLivro)
                            .addComponent(jbtnRemoverLivro)
                            .addComponent(jbtnAlterarLivro)
                            .addComponent(jbtnListarTudo))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jlpAcervoLayout.setVerticalGroup(
            jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcervoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jbtnPesquisar))
                .addGroup(jlpAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAcervoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpAcervoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jbtnAddLivro)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnRemoverLivro)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnAlterarLivro)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnListarTudo))))
        );
        jlpAcervo.setLayer(jtxtfTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jbtnPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jbtnListarTudo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jbtnAddLivro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jbtnRemoverLivro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcervo.setLayer(jbtnAlterarLivro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jbtnPesquisarUser.setText("Pesquisar usuário");

        jLabel4.setText("Matrícula:");

        jbtnAdicionarUser.setText("Adicionar usuário");
        jbtnAdicionarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarUserActionPerformed(evt);
            }
        });

        jbtnRemoverUser.setText("Remover usuário");
        jbtnRemoverUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverUserActionPerformed(evt);
            }
        });

        jbtnAlterarUser.setText("Alterar usuário");
        jbtnAlterarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarUserActionPerformed(evt);
            }
        });

        jbtnListarTodos.setText("Listar todos os usuários");

        javax.swing.GroupLayout jlpSistemaLayout = new javax.swing.GroupLayout(jlpSistema);
        jlpSistema.setLayout(jlpSistemaLayout);
        jlpSistemaLayout.setHorizontalGroup(
            jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpSistemaLayout.createSequentialGroup()
                .addGroup(jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpSistemaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbtnAlterarUser)
                            .addComponent(jbtnListarTodos)
                            .addComponent(jbtnRemoverUser)
                            .addComponent(jbtnAdicionarUser)))
                    .addGroup(jlpSistemaLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPesquisarUser)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jlpSistemaLayout.setVerticalGroup(
            jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpSistemaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPesquisarUser)
                    .addComponent(jLabel4))
                .addGroup(jlpSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpSistemaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpSistemaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jbtnAdicionarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoverUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnAlterarUser)
                        .addGap(12, 12, 12)
                        .addComponent(jbtnListarTodos)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jlpSistema.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jbtnPesquisarUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jbtnAdicionarUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jbtnRemoverUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jbtnAlterarUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpSistema.setLayer(jbtnListarTodos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAcervo)
                .addGap(18, 18, 18)
                .addComponent(jbtnSistema))
            .addComponent(jlpSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jlpAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSistema)
                    .addComponent(jbtnAcervo)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlpSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAcervoActionPerformed
        jlpAcervo.setVisible(true);
        jlpSistema.setVisible(false);
    }//GEN-LAST:event_jbtnAcervoActionPerformed

    private void jbtnRemoverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRemoverLivroActionPerformed

    private void jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPesquisarActionPerformed

    private void jbtnListarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListarTudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListarTudoActionPerformed

    private void jtxtfTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfTituloActionPerformed

    private void jbtnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSistemaActionPerformed
        jlpAcervo.setVisible(false);
        jlpSistema.setVisible(true);
    }//GEN-LAST:event_jbtnSistemaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbtnAlterarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAlterarUserActionPerformed

    private void jbtnRemoverUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRemoverUserActionPerformed

    private void jbtnAdicionarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdicionarUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jlpAcervo.setVisible(false);
        jlpSistema.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jbtnAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAlterarLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogadoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAcervo;
    private javax.swing.JButton jbtnAddLivro;
    private javax.swing.JButton jbtnAdicionarUser;
    private javax.swing.JButton jbtnAlterarLivro;
    private javax.swing.JButton jbtnAlterarUser;
    private javax.swing.JButton jbtnListarTodos;
    private javax.swing.JButton jbtnListarTudo;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JButton jbtnPesquisarUser;
    private javax.swing.JButton jbtnRemoverLivro;
    private javax.swing.JButton jbtnRemoverUser;
    private javax.swing.JButton jbtnSistema;
    private javax.swing.JLayeredPane jlpAcervo;
    private javax.swing.JLayeredPane jlpSistema;
    private javax.swing.JTextField jtxtfTitulo;
    // End of variables declaration//GEN-END:variables
}
