/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

/**
 *
 * @author filipe
 */
public class alugarLivroGUI extends javax.swing.JFrame {

    /**
     * Creates new form alugarLivroGUI
     */
    public alugarLivroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jbtnVoltar = new javax.swing.JButton();
        jbtnAlugar = new javax.swing.JButton();
        jlblID = new javax.swing.JLabel();
        jlblEntrega = new javax.swing.JLabel();
        jtxtfID = new javax.swing.JTextField();
        jlblAutor = new javax.swing.JLabel();
        jlblEditora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblName = new javax.swing.JLabel();
        jlblMatricula = new javax.swing.JLabel();
        jlblTipo = new javax.swing.JLabel();
        jtxtfName = new javax.swing.JTextField();
        jtxtfMatricula = new javax.swing.JTextField();
        jtxtfTipo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jtxtfAutor = new javax.swing.JTextField();
        jtxtfEditora = new javax.swing.JTextField();
        jlblAluguel = new javax.swing.JLabel();
        jtxtfAluguel = new javax.swing.JTextField();
        jtxtfTitulo = new javax.swing.JTextField();
        jtxtfEntrega = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 18)); // NOI18N
        jLabel13.setText("Informações do livro");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 205, -1));

        jbtnVoltar.setText("Voltar");
        jbtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jbtnAlugar.setText("Alugar Livro");
        getContentPane().add(jbtnAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jlblID.setText("ID:");
        getContentPane().add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 271, -1, -1));

        jlblEntrega.setText("Entrega:");
        getContentPane().add(jlblEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 231, -1, -1));

        jtxtfID.setEditable(false);
        getContentPane().add(jtxtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 266, 251, -1));

        jlblAutor.setText("Autor:");
        getContentPane().add(jlblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 105, -1, -1));

        jlblEditora.setText("Editora:");
        getContentPane().add(jlblEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 145, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlblName.setText("Nome:");

        jlblMatricula.setText("Matrícula:");

        jlblTipo.setText("Tipo:");

        jtxtfName.setEditable(false);
        jtxtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfNameActionPerformed(evt);
            }
        });

        jtxtfMatricula.setEditable(false);

        jtxtfTipo.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Nimbus Roman No9 L", 1, 18)); // NOI18N
        jLabel11.setText("Informações do usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTipo)
                    .addComponent(jlblMatricula)
                    .addComponent(jlblName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jtxtfMatricula)
                    .addComponent(jtxtfTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblName)
                    .addComponent(jtxtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMatricula)
                    .addComponent(jtxtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTipo)
                    .addComponent(jtxtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        jlblTitulo.setText("Título:");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 65, -1, -1));

        jtxtfAutor.setEditable(false);
        jtxtfAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfAutorActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtfAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 251, -1));

        jtxtfEditora.setEditable(false);
        getContentPane().add(jtxtfEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 251, -1));

        jlblAluguel.setText("Aluguel:");
        getContentPane().add(jlblAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 191, -1, -1));

        jtxtfAluguel.setEditable(false);
        getContentPane().add(jtxtfAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 186, 251, -1));

        jtxtfTitulo.setEditable(false);
        getContentPane().add(jtxtfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 251, -1));

        jtxtfEntrega.setEditable(false);
        getContentPane().add(jtxtfEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 226, 251, -1));

        setSize(new java.awt.Dimension(829, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnVoltarActionPerformed

    private void jtxtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfNameActionPerformed

    private void jtxtfAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alugarLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alugarLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alugarLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alugarLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alugarLivroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAlugar;
    private javax.swing.JButton jbtnVoltar;
    private javax.swing.JLabel jlblAluguel;
    private javax.swing.JLabel jlblAutor;
    private javax.swing.JLabel jlblEditora;
    private javax.swing.JLabel jlblEntrega;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblMatricula;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtfAluguel;
    private javax.swing.JTextField jtxtfAutor;
    private javax.swing.JTextField jtxtfEditora;
    private javax.swing.JTextField jtxtfEntrega;
    private javax.swing.JTextField jtxtfID;
    private javax.swing.JTextField jtxtfMatricula;
    private javax.swing.JTextField jtxtfName;
    private javax.swing.JTextField jtxtfTipo;
    private javax.swing.JTextField jtxtfTitulo;
    // End of variables declaration//GEN-END:variables
}
