/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

import codigoFonte.Acervo;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import codigoFonte.Acervo;
import codigoFonte.Livro;
//import codigoFonte.Sistema;
import codigoFonte.User;
import java.util.ArrayList;
        

/**
 *
 * @author filipe
 */
public class userLogadoGUI extends javax.swing.JFrame {

    /**
     * Creates new form userLogadoGUI
     */
    public userLogadoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jlblNome = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jlblMatricula = new javax.swing.JLabel();
        jlblTipo = new javax.swing.JLabel();
        jtxtfNome = new javax.swing.JTextField();
        jtxtfMatricula = new javax.swing.JTextField();
        jtxtfTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(876, 369, 259, 28);

        jlblNome.setText("Nome:");
        getContentPane().add(jlblNome);
        jlblNome.setBounds(80, 17, 46, 18);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Livro", "Editora", "Autor", "Dia do alguel", "Dia de entrega", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(228, 168, 862, 80);

        jlblMatricula.setText("Matrícula:");
        getContentPane().add(jlblMatricula);
        jlblMatricula.setBounds(80, 63, 69, 18);

        jlblTipo.setText("tipo:");
        getContentPane().add(jlblTipo);
        jlblTipo.setBounds(80, 109, 31, 18);

        jtxtfNome.setEditable(false);
        jtxtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtfNome);
        jtxtfNome.setBounds(170, 20, 237, 28);

        jtxtfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtfMatricula);
        jtxtfMatricula.setBounds(170, 60, 237, 28);

        jtxtfTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtfTipo);
        jtxtfTipo.setBounds(170, 100, 241, 28);

        setSize(new java.awt.Dimension(1363, 827));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfNomeActionPerformed
        Acervo acervo = new Acervo();
        ArrayList<Livro> livros = acervo.pesquisarLivro("A Fúria Dos Reis - As Crônicas de Gelo e Fogo - Vol. 2");
        
        jtxtfNome.setText(livros.get(0).getEditora());
    }//GEN-LAST:event_jtxtfNomeActionPerformed

    private void jtxtfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfMatriculaActionPerformed

    private void jtxtfTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfTipoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Acervo acervo = new Acervo();
        ArrayList<Livro> livros = acervo.pesquisarLivro("A Fúria Dos Reis - As Crônicas de Gelo e Fogo - Vol. 2");
        
        jtxtfNome.setText(livros.get(0).getEditora());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLogadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLogadoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlblMatricula;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JTextField jtxtfMatricula;
    private javax.swing.JTextField jtxtfNome;
    private javax.swing.JTextField jtxtfTipo;
    // End of variables declaration//GEN-END:variables
}
